ci: fail if the generation fails, unless the project is allowed to fail

diff --git a/.github/workflows/main.yml b/.github/workflows/main.yml
--- a/.github/workflows/main.yml
+++ b/.github/workflows/main.yml
@@ -25,6 +25,7 @@ jobs:
 
       - name: Run generate.sh in each directory and commit changes
         run: |
+          allowed_to_fail=("sumatra/")
           for d in */; do
             if [ -f "${d}generate.sh" ]; then
               echo "Running generate.sh in $d"
@@ -38,7 +39,13 @@ jobs:
                   git checkout "$d"
                 fi
               else
-                echo "generate.sh failed in $d, skipping..."
+                echo "generate.sh failed in $d"
+                if [[ " ${allowed_to_fail[@]} " =~ " ${d} " ]]; then
+                  echo "$d failed but is whitelisted, continuing..."
+                else
+                  echo "Stopping execution due to failure in $d"
+                  exit 1
+                fi
                 git checkout "$d"
               fi
               git clean -f
